# Generated by Django 5.1.1 on 2024-09-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Shakes', 'Shakes'), ('Juices', 'Juices'), ('Chinese', 'Chinese'), ('Arabic', 'Arabic'), ('Curry', 'Curry'), ('Mandhi', 'Mandhi')], default='Shakes', max_length=50),
            preserve_default=False,
        ),
    ]
