# Generated by Django 5.1.1 on 2024-10-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='method',
            field=models.CharField(choices=[('Dine-In', 'Dine-In'), ('Take-out', 'Take-out')], default='Dine-In', max_length=20),
        ),
    ]
