# Generated by Django 5.1.1 on 2024-10-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0010_booking_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table_number',
        ),
    ]
