# Generated by Django 5.1.1 on 2024-10-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0012_booking_dish_price_booking_dishes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dishes',
            field=models.JSONField(default=list),
        ),
    ]
