# Generated by Django 5.1.1 on 2024-10-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0013_alter_booking_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dish_price',
        ),
    ]
