# Generated by Django 5.1.1 on 2024-10-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0014_remove_booking_dish_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dish',
        ),
    ]
