# Generated by Django 5.1.1 on 2024-10-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0017_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
