# Generated by Django 5.1.1 on 2024-10-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0019_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='max_capacity',
            field=models.IntegerField(default=10),
        ),
    ]
