# Generated by Django 5.1.1 on 2024-10-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0020_timeslot_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='max_capacity',
            field=models.IntegerField(),
        ),
    ]
