# Generated by Django 5.1.1 on 2024-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0021_alter_timeslot_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='bookings_count',
            field=models.IntegerField(default=0),
        ),
    ]
