# Generated by Django 5.1.1 on 2024-10-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0023_alter_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', max_length=10),
        ),
    ]
