# Generated by Django 5.1.1 on 2024-10-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0024_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='nonveg', max_length=10),
        ),
    ]
