# Generated by Django 5.1.1 on 2024-10-08 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouterapp', '0004_order_orderitem'),
        ('sellerapp', '0018_remove_cart_dish_remove_cart_user_delete_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.IntegerField()),
                ('bookings_count', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller')),
            ],
        ),
    ]
