# Generated by Django 5.1.1 on 2024-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouterapp', '0006_order_created_at_delete_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
